version: "3.2"
services:
  db:
    image: mysql:8.0.27
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "4231"
      MYSQL_DATABASE: "sami"
    ports:
      - 3306:3306
    entrypoint: sh -c "
      echo 'CREATE DATABASE IF NOT EXISTS sami; CREATE DATABASE IF NOT EXISTS samitest;' > /docker-entrypoint-initdb.d/init.sql;
      /usr/local/bin/docker-entrypoint.sh --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
      "
    volumes:
      - datavolume:/var/lib/mysql
  api:
    image: node:14.18-alpine3.13
    container_name: api
    tty: true
    depends_on:
      - db
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: sh
    links:
      - db
volumes:
  datavolume:
